// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVpKEC_Y9TT7zbnIO_WSMyG4-DMEcVwuo',
    appId: '1:756523290246:web:598c0a61163f0ce52c0b07',
    messagingSenderId: '756523290246',
    projectId: 'financeapp-5ce80',
    authDomain: 'financeapp-5ce80.firebaseapp.com',
    storageBucket: 'financeapp-5ce80.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvASjFA7emCr8FFaUuJ6KOnQ7qXWlI-r0',
    appId: '1:756523290246:android:bf66363203252d8b2c0b07',
    messagingSenderId: '756523290246',
    projectId: 'financeapp-5ce80',
    storageBucket: 'financeapp-5ce80.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApie4zHaoN1jkgdEQh4xq5WAYIRohyjMM',
    appId: '1:756523290246:ios:f7adbbab137b69b02c0b07',
    messagingSenderId: '756523290246',
    projectId: 'financeapp-5ce80',
    storageBucket: 'financeapp-5ce80.appspot.com',
    iosBundleId: 'com.example.medicineApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyApie4zHaoN1jkgdEQh4xq5WAYIRohyjMM',
    appId: '1:756523290246:ios:719f84e8319762742c0b07',
    messagingSenderId: '756523290246',
    projectId: 'financeapp-5ce80',
    storageBucket: 'financeapp-5ce80.appspot.com',
    iosBundleId: 'com.example.medicineApp.RunnerTests',
  );
}
